runtime: python39

# service: wcs-html-responsive
service: wcs-html-e-apostilles-new

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)